[application]
name = "gantry"

[web.app]
title = "Gantry"

[bundle]
identifier = "io.github.cascalheira.gantry"
publisher = "Gantry"
icon = ["assets/icon.icns", "assets/icon.ico", "assets/icon-1024.png"]
